version: '3.8'

services:
  mongo-db-cont:
    image: mongo:latest
    container_name: mongo-db-cont
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"

  mongo-express-cont:
    image: mongo-express:latest
    container_name: mongo-express-cont
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db-cont
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo-db-cont
